language: java
sudo: required
dist: trusty

services:
  - mysql

env:
  global:
    - RELEASE_VERSION="1.1.0"
    - RELEASE_PLACEHOLDER="@release.number@"
    - BUILD_PLACEHOLDER="@build.number@"

before_install:
  - mysql < tests/resources/Dump_All_Types.sql

  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
  - sudo apt-get update && sudo apt-get install commandbox
  - mkdir modules
  - mkdir modules/cfboom-opencsv
  - mv apidocs/  modules/cfboom-opencsv/
  - mv lib/ modules/cfboom-opencsv/
  - mv tests/ modules/cfboom-opencsv/
  - mv box.json modules/cfboom-opencsv/
  - mv CSVReader.cfc modules/cfboom-opencsv/
  - mv CSVWriter.cfc modules/cfboom-opencsv/
  - mv LICENSE modules/cfboom-opencsv/
  - mv ModuleConfig.cfc modules/cfboom-opencsv/
  - mv PassthroughSanitizer.cfc modules/cfboom-opencsv/
  - mv README.md modules/cfboom-opencsv/
  - mv Sanitizer.cfc modules/cfboom-opencsv/

install:
  - box coldbox create app
  - box install coldbox
  - box install testbox
  - box install cbjavaloader
  - box install cfboom-lang
  - box install cfboom-util
  - box server start port=45123 rewritesEnable=true JVMArgs="-DcfAdminPassword=J5HIsmsWk26" openBrowser=false

before_script:
  - curl http://localhost:45123/
  - curl --data "new_password=J5HIsmsWk26&new_password_re=J5HIsmsWk26&lang=en&rememberMe=s&submit=submit" http://localhost:45123/lucee/admin/web.cfm
  - curl http://localhost:45123/modules/cfboom-opencsv/tests/travis_db.cfm

script: > 
    testResults="echo $(box testbox run runner=http://localhost:45123/modules/cfboom-opencsv/tests/runner.cfm)";
    echo "$testResults";
    if grep -i "\[Failures: [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi

after_success:
  - sudo sed -i "s/$RELEASE_PLACEHOLDER/${RELEASE_VERSION}/g;" 'modules/cfboom-opencsv/box.json'
  - sleep 2
  - sudo sed -i "s/$BUILD_PLACEHOLDER/${TRAVIS_BUILD_NUMBER}/g" 'modules/cfboom-opencsv/box.json'
  - sleep 2
