language: java
sudo: required
dist: trusty

env:
  global:
    - RELEASE_VERSION="1.0.0"
    - RELEASE_PLACEHOLDER="@release.number@"
    - BUILD_PLACEHOLDER="@build.number@"

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
  - sudo apt-get update && sudo apt-get install commandbox
  - mkdir modules
  - mkdir modules/cfboom-http
  - mv apidocs/  modules/cfboom-http/
  - mv tests/ modules/cfboom-http/
  - mv client/ modules/cfboom-http/
  - mv message/ modules/cfboom-http/
  - mv protocol/ modules/cfboom-http/
  - mv box.json modules/cfboom-http/
  - mv HttpMessage.cfc modules/cfboom-http/
  - mv HttpRequest.cfc modules/cfboom-http/
  - mv HttpResponse.cfc modules/cfboom-http/
  - mv HttpStatus.cfc modules/cfboom-http/
  - mv LICENSE modules/cfboom-http/
  - mv ModuleConfig.cfc modules/cfboom-http/
  - mv README.md modules/cfboom-http/
  - mv RequestParam.cfc modules/cfboom-http/

install:
  # create app 2x to ensure no time outs
  - box coldbox create app
  - box coldbox create app
  # install coldbox 2x to ensure no time outs. It skips if coldbox is already installed.
  - box install coldbox
  - box install coldbox
  # install testbox 2x to ensure no time outs. It skips if testbox is already installed.
  - box install testbox
  - box install testbox
  # install cfboom-lang 2x to ensure no time outs. It skips if cfboom-lang is already installed.
  - box install cfboom-lang
  - box install cfboom-lang
  - box server start port=45123 openBrowser=false

before_script:
  - curl http://localhost:45123/

script: > 
    testResults="echo $(box testbox run runner=http://localhost:45123/modules/cfboom-http/tests/runner.cfm)";
    echo "$testResults";
    if grep -i "\[Failures: [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi

after_success:
  - sudo sed -i "s/$RELEASE_PLACEHOLDER/${RELEASE_VERSION}/g;" 'modules/cfboom-http/box.json'
  - sleep 2
  - sudo sed -i "s/$BUILD_PLACEHOLDER/${TRAVIS_BUILD_NUMBER}/g" 'modules/cfboom-http/box.json'
  - sleep 2
